### ISSUE TITLE
Naming, Branding and Logo

### ISSUE THREAD

**Issue by antfu** [windicss/windicss#20]
I feel there is a huge potential for this project in the near future and it will be compared with Tailwind quite frequently. I think it's nice to have a good naming conversion and some logo and branding stuff now.

## Naming Conversion

I saw you are mention this project mostly as `windicss` while the official name for tailwind is `Tailwind CSS`. Would love to know what' the naming conversion you'd prefer:

- windicss
- Windi CSS
- WindiCSS
- WindiCss

I personally would pick `Windi CSS` as it matches with tailwind's and in many context we can have `Windi vs Tailwind` or `Tailwind CSS and Windi CSS`. The current lowercase one feels less like a tool's name - `windicss vs Tailwind CSS`.

## Brand Color

Clearly, Tailwind uses teal(#06b6d4) as its brand color. Guess we should also pick up a color for Windi so it can be better comparable.

Do you have any color in mind?

## Logo

Wondering what's the meaning/inspiration for the name `windi`? If you'd like to, I am happy to draft some logo designs for it.

Would love to hear what you think about this, thanks!

**Comment by antfu** [comment]
BTW, I have just secured the npm namespace [@windicss](https://www.npmjs.com/org/windicss) and GitHub org [windicss](https://github.com/windicss) for the potential growth of this project. Can you have your npm id so I can give your permission? (just in case you might need them in the future, not trying to push anything)

**Comment by voorjaar** [comment]
Thank you for doing so much. Does npm id means email or what?

**Comment by voorjaar** [comment]
https://www.npmjs.com/~voorjaar

**Comment by voorjaar** [comment]
It looks weird if the name are separated. Tailwind is also tailiwindcss most of the time. Look at their [logo](https://camo.githubusercontent.com/53b9876cd8e38928387c6824043b0e2772b15b1bfdb7f42d0864216abbf3dfe8/68747470733a2f2f7265666163746f72696e6775692e6e7963332e63646e2e6469676974616c6f6365616e7370616365732e636f6d2f7461696c77696e642d6c6f676f2e737667)

About the name, you know that there is a movie called Billions and the heroine is called Wendy, so I took a windi, which is also very close to tailwind.

Colors that I prefer:

#339AF0

#5335EF

#7F9CF5

Since you are a designer, you can choose the colors according to the graphics.

**Comment by antfu** [comment]
> npm id

Sent. Let me know when you accepted it so I can update the role.

> name

Sounds reasonable. Are you ok with calling it Windi for most of the time (refer to Tailwind)? Imagine this page https://tailwindcss.com/ but replace all the `Tailwind` to `Windi`, would the usages good to you?

> logo

Sure, I will give it a try bit might take some time. I think we should also welcome proposals from the community ;)
