### ISSUE TITLE
Feature: dynamic class adding with @apply directive (similar to compose of css module)

### ISSUE THREAD

**Issue by angrotheman** [windicss/windicss#225]
I've been thinking about this feature for a while now, but with tailwind this can't work. But maybe with windicss?

Sometimes it is cleaner to use the @apply directive. For example, to shorten the line length or to refer the same styling in a component without duplicating the same classes. My disadvantage with @apply is, that it generates a whole new class with the styling that is usually already there. In larger projects this will end up in a larger css file than if only the pure tailwind classes were used. But what would be, if @apply didn't generate a new class but an array of classes that the object needs and add them dynamically? Similar to the [compose method of css modules](https://github.com/css-modules/css-modules#composition) 

I think this is an incredible improvement! 

Here is an example of what my idea might look like:
This is the Code I am writing:
```
<div class="btn" /> 
<style>
  .btn {
    @apply w-4 h-4 bg-blue-500;
  }
</style>
```

and this is what the compiled code looks like:
```
<div class="w-4 h-4 bg-blue-500" />
```

**Comment by ahku** [comment]
This is a great idea, but the example syntax would not work as `.btn` might be used by other styles eyes due to the implicit nature of css.

Would it be possible to borrow the css modules syntax, ie create a component-scoped helper:

``` html
<template>
  <button :class="$style.button" />
</template>

<style module>
  .button {
    @apply text-red-500;
  }
</style>
```

Otherwise, it might be easier to just do some string concatenation.

**Comment by ahku** [comment]
What do you guys think about this? 

The great thing about @angrotheman's idea is that it would still feel like writing standard CSS, and maybe it would be more intuitive to compose component like this. Not sure what the best, universal approach is. 

Maybe we could prefix these "class name variables" with `$`:

```html
<button class="$button $button--primary">Click here</button

<style>
.\$button {
  @apply py-2 px-4 font-bold text-sm;
}

.\$button--primary {
  @apply py-2 px-4 font-bold text-sm bg-blue-600 text-white;
}
</style>

```

(The above example makes me want to be able to set default background and foreground color that can be overridden like with normal css when the `--primary` variant is set, but it might be too complicated since we need to check the _function_ of each class name)

Anyway, the above API is still not as nice as the original approach, since it's annoying to type `.\$button`. Would be cool if you could do this:

```html
<button class="$button $button--primary">Click here</button

<style>
@shortcuts {
  .button {
    @apply py-2 px-4 font-bold text-sm;
  }

  .button--primary {
    @apply py-2 px-4 font-bold text-sm bg-blue-600 text-white;
  }
}
</style>
```

I realize that you could probably just use the built in shortcuts feature (not sure if it also expands all the classes?) at this point, but there's a convenience in being able to add shortcuts as you go, in the right context, scoped.

The best would be if you could specify the shortcuts directly with javascript (no need for @apply), but I have no idea how that would work, so I leave it to people smarter than me :)

```html
<button class="$button $button--primary">Click here</button

<script>
shortcuts: {
  button: 'py-2 px-4 font-bold text-sm',
 'button--primary': 'py-2 px-4 font-bold text-sm bg-blue-600 text-white'
}
</script>
```

Alternative naming conventions:

``` html
<!-- Curly brackets -->
<button class="{button} {button--primary}">Click here</button

<!-- <tag> -->
<button class="<button> <button--primary>">Click here</button

```

**Comment by mgutz** [comment]
The `@apply` feature and I think shortcuts create a new CSS rule if I'm reading the docs correctly. That feature seems to against the spirit of tailwind, which constrains styling to a small set of atomic rules.

The workaround I use for shared patterns

```javascript
const styles = {
    btn: 'w-4 h-4 bg-blue-500'
}

//  somewhat icky to look at
return <button className={`${styles.btn} text-white`}>Click me</button>
```

Expanding on the ideas here, it would be nice to have a shortcode feature to expand the shortcode token with its definition. Maybe something like this  

```javascript
/// windi.config.js
{
    ...
   shortcodes: {
       btn: 'w-4 h-4 bg-blue-500'
   }
}

/// in your component
// % is an arbitrary sigil for shortcode
<button className="%btn text-white">Click me</button>
```

**Comment by ahku** [comment]
@mgutz check out the new alias config: https://windicss.org/posts/v30.html#alias-config

**Comment by antfu** [comment]
I think the alias config is what you are looking for. Close for now

**Comment by mgutz** [comment]
great minds think alike :) Thank you for this wonderful utility!
