### ISSUE TITLE
WindiCSS Docs search not working properly.

### ISSUE THREAD

**Issue by BroJenuel** [windicss/windicss#794]
I am using WindiCSS a lot,, and I always go to WindiCSS docs and use search to find utilities I like to use.. just today it seems like the search not working properly

I am looking for hover but does not work properly.

![image](https://user-images.githubusercontent.com/31676163/173185818-d724014f-f103-49c2-b6e3-b2397f6af2da.png)

**Comment by supergoat** [comment]
Doesn't work at all now. It seems it's a problem with algolia.
```Operations quota exceeded. Change plan to get more Operations.```

**Comment by lctech-mike** [comment]
This question how to fix?

**Comment by MikeCheng1208** [comment]
This question how to fix?

**Comment by jamcmich** [comment]
I'm having the same issue. From what I can tell in the browser console and a quick Google search, it seems like WindiCSS has exceeded their search quota with the Algolia service used for browsing the docs. Since it seems like this issue appeared for me almost a month later, I'm assuming this happens sometimes at the end of their monthly quota period. I'm sure it will be fixed soon!

In the meantime, you can still use the navigation menus at the top of the screen to find what you're looking for. I stumbled upon some cool features by circumventing the quick search utility, such as the [WindiCSS Intellisense extension for VS Code](https://windicss.org/editors/vscode.html), which I didn't know existed until now.

**Comment by BroJenuel** [comment]
it seems its now working on my end so I will be closing this issue.
