### ISSUE TITLE
is windicss dead?

### ISSUE THREAD

**Issue by arlanram** [windicss/windicss#858]
is windicss dead?

**Comment by jonorozcoc** [comment]
People prefer using Tailwind's JIT compiler. Additionally, there are many features missing on Windi compared to the latest version of Tailwind

**Comment by Nyaacinth** [comment]
Since the project [UnoCSS](https://github.com/unocss/unocss) is announced at [Reimagine Atomic CSS](https://antfu.me/posts/reimagine-atomic-css), seems like WindiCSS project support has been dropped.
Maybe you can think about migrating to UnoCSS, it has a preset supports most of class utility that WindiCSS provided.

**Comment by kamontat** [comment]
https://antfu.me/posts/reimagine-atomic-css#what-about-windi-css

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/windicss/issues/904
